package eu.wohlben.qits.containers.entity;

import eu.wohlben.qits.containers.driver.spec.LifecyclePolicy;
import eu.wohlben.qits.eventstream.CausationStamp;
import eu.wohlben.qits.eventstream.CausedRow;
import io.quarkus.hibernate.orm.panache.PanacheEntityBase;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Duration;
import java.time.Instant;
import java.util.UUID;

/**
 * One container this service is responsible for — <b>the row that exists before the container
 * does</b>.
 *
 * <p>That ordering is the whole repository. {@code ContainerRegistry.ensure} commits this row with
 * {@link #containerName} already chosen and {@link #observedState} {@code PENDING}, and only then
 * calls {@code docker run}. A crash anywhere after that leaves a container the registry can still
 * name, which is what lets a restart <b>adopt</b> rather than guess — and it is why no code path in
 * this service removes a container that no row names.
 *
 * <p><b>{@link #ownerRef} plus {@link #owner} plus {@link #workload} is the PLACE</b> a container
 * occupies. V1's partial unique index allows one live row per place; a deleted row keeps its history
 * with {@code desired_state = 'ABSENT'} and frees the place the moment it is set.
 *
 * <p><b>{@link #specJson} never contains the spec's environment.</b> Env carries credentials — a
 * registry token, a database password, a machine token minted for one step — and this table would
 * otherwise be the platform's largest collection of them. {@link #specHash} <em>is</em> computed
 * over a canonical form that includes env, so "has this workload changed" stays answerable without a
 * credential ever having been stored. Hash yes, plaintext no.
 *
 * <p><b>A {@link CausedRow}, and the stamp is the mechanism rather than an explicit set.</b> The one
 * insert this table has is {@code ensure}, which runs on the caller's own thread — the REST worker
 * once WP4 lands, a test thread today — with no queue and no executor between the request and the
 * {@code persist}. {@code @PrePersist} fires at {@code persist()} on the calling thread, so the
 * ambient {@code CausationScope} the REST filter restored is still standing when the listener reads
 * it. Everything else here is an <em>update</em> — the sweeps and the observer settle states — and
 * causation is insert-only by design, so none of those writes has a cause to record.
 *
 * <p>Measured on this schema, 2026-08-11: a row persisted inside a {@code CausationScope} reads its
 * {@code causation_id} back non-null, so the stamp fires despite Hibernate's augmentation warning
 * that {@code CausationStamp} is claimed by no named persistence unit — the listener is resolved
 * from the annotation rather than from a package claim. {@code CtCausationStampTest} is that
 * measurement, and it is written to fail if the listener ever stops firing; a background writer that
 * ever <em>inserts</em> one of these rows must set the cause as data instead, the way qits-ci's
 * {@code CiRun} does across its queue hop.
 */
@Entity
@Table(name = "ct_container")
@EntityListeners(CausationStamp.class)
public class CtContainer extends PanacheEntityBase implements CausedRow {

  /** Application-assigned, and the value the container carries back as its {@code row} label. */
  @Id public UUID id;

  /**
   * Insertion order, for listings that must not depend on a random UUID to break a tie. Generated by
   * the database, so it is read but never written.
   */
  @Column(insertable = false, updatable = false)
  public Long seq;

  /** The calling service ({@code qits-ci}, {@code qits-workspaces}) — the scope of every call. */
  @Column(nullable = false, length = 64)
  public String owner;

  /** What kind of thing this is to that owner ({@code step}, {@code workspace}). */
  @Column(nullable = false, length = 64)
  public String workload;

  /** The owner's own id for the place: a run id, a workspace id. Opaque here. */
  @Column(name = "owner_ref", nullable = false, length = 190)
  public String ownerRef;

  /**
   * The docker name, unique <b>among live rows</b> because docker's namespace is. It is chosen
   * before the run and is what every later inspect, stop and remove addresses — never a label
   * filter.
   *
   * <p>V3 made that uniqueness partial, the way the place already was. A settled row keeps the name
   * it ran under so its history reads, and the name is free the moment the place is — without which
   * a deleted place could not be started again until the prune horizon passed, because the name is
   * derived from the place and comes out the same every time.
   */
  @Column(name = "container_name", nullable = false, length = 190)
  public String containerName;

  /** The image as it was run, kept out of {@link #specJson} because every listing shows it. */
  @Column(nullable = false, columnDefinition = "text")
  public String image;

  /** The spec as persisted — <b>without env</b>. See the class javadoc. */
  @Column(name = "spec_json", nullable = false, columnDefinition = "text")
  public String specJson;

  /** sha256 over the canonical spec <b>including</b> env. See the class javadoc. */
  @Column(name = "spec_hash", nullable = false, length = 64)
  public String specHash;

  @Enumerated(EnumType.STRING)
  @Column(nullable = false, length = 32)
  public LifecyclePolicy.Type policy;

  /** Seconds an {@code IDLE_STOP} workload may go untouched. Null for the policies that never idle. */
  @Column(name = "idle_after_s")
  public Long idleAfterS;

  /**
   * Seconds an {@code EPHEMERAL} workload may live before it is collected. Null means no such sweep.
   * Added in V2: V1 carried only {@code idle_after_s}, and a policy value the sweeps read has to be
   * on the row rather than in the caller's memory, or a restart forgets it.
   */
  @Column(name = "max_age_s")
  public Long maxAgeS;

  @Enumerated(EnumType.STRING)
  @Column(name = "desired_state", nullable = false, length = 16)
  public DesiredState desiredState;

  @Enumerated(EnumType.STRING)
  @Column(name = "observed_state", nullable = false, length = 16)
  public ObservedState observedState;

  @Column(name = "created_at", nullable = false)
  public Instant createdAt;

  @Column(name = "updated_at", nullable = false)
  public Instant updatedAt;

  /** When the observer last got an answer about this container. Null until the first pass. */
  @Column(name = "last_observed_at")
  public Instant lastObservedAt;

  /**
   * When the owner last said it still wants this workload. Null until the first touch — and the idle
   * sweep <b>stamps it on sight</b> rather than reading a null as "never used", so a container this
   * process has not heard from ages out one window later instead of being stopped the moment it is
   * first seen.
   */
  @Column(name = "last_touched_at")
  public Instant lastTouchedAt;

  /** Append-only human text: why a row failed, what the last docker call said. Newest line first. */
  @Column(columnDefinition = "text")
  public String detail;

  /** The platform's generic trace column. See the class javadoc; part of no constraint. */
  @Column(name = "causation_id")
  public UUID causationId;

  @Override
  public UUID causationId() {
    return causationId;
  }

  @Override
  public void causationId(UUID id) {
    this.causationId = id;
  }

  /**
   * The policy this row is swept under, reassembled from its three columns.
   *
   * <p>Named {@code lifecyclePolicy()} rather than {@code policy()} so it cannot be mistaken for an
   * accessor of the field beside it — this entity is field-accessed and a getter-shaped method would
   * be one more thing to reason about when Hibernate picks an access strategy.
   */
  public LifecyclePolicy lifecyclePolicy() {
    return new LifecyclePolicy(
        policy,
        idleAfterS == null ? null : Duration.ofSeconds(idleAfterS),
        maxAgeS == null ? null : Duration.ofSeconds(maxAgeS));
  }
}
